name: Docker Image CI (Airflow)

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd tutorials/airflow
        docker build --tag ploomber-airflow .
    - name: Start a Docker container
      run: |
        export SHARED_DIR=$HOME/ploomber-workflow
        rm -rf $SHARED_DIR
        mkdir -p $SHARED_DIR
        docker run -p 8080:8080 --privileged=true \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --volume $SHARED_DIR:/mnt/shared-folder \
            --env SHARED_DIR \
            --env PLOOMBER_STATS_ENABLED=false \
            ploomber-airflow /bin/bash