apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: argo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi