apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # set programatically
  generateName: null

spec:
  entrypoint: dag

  volumes:
  - name: workdir
    # FIXME: this should be a parameter
    persistentVolumeClaim:
      claimName: nfs

  templates:
  - name: run-task
    inputs:
      parameters:
      - name: task_name
    script:
      image: continuumio/miniconda3
      command: [bash]
      source: |
        set -e
        # TODO: should cd to the project root
        cd /mnt/vol/ml-basic
        # TODO: install stable versions once they're released
        pip install git+https://github.com/ploomber/ploomber@dev
        pip install git+https://github.com/ploomber/soopervisor@dev-edu
        python -m soopervisor.script.ScriptConfig "ploomber task {{inputs.parameters.task_name}}" > script.sh
        bash script.sh
      volumeMounts:
          # FIXME: this should also be a parameter
          # reference: https://argoproj.github.io/argo/fields/#volumemount
        - name: workdir
          mountPath: /mnt/vol

  - name: dag
    dag:
      tasks: null