apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # set programatically
  generateName: null

spec:
  entrypoint: dag

  volumes:
  - name: nfs-volume
    # FIXME: this should be a parameter
    persistentVolumeClaim:
      claimName: nfs

  templates:
  - name: run-task
    inputs:
      parameters:
      - name: task_name
    script:
      image: continuumio/miniconda3
      command: [bash]
      workingDir: /mnt/vol
      source: |
        set -e
        # TODO: remove this once I make a soopervisor release, installing
        # soopervisor installs ploomber
        pip install ploomber
        # TODO: install stable versions once they're released
        pip install git+https://github.com/ploomber/soopervisor@dev-edu
        python -m soopervisor.script.ScriptConfig "ploomber task {{inputs.parameters.task_name}} --force" > script.sh
        bash script.sh
      volumeMounts:
          # reference: https://argoproj.github.io/argo/fields/#volumemount
        - name: nfs-volume
          mountPath: /mnt/vol
          subPath: null

  - name: dag
    dag:
      tasks: null