name: CI TEST

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CI TEST
      run: |
        echo $HOME
        export SHARED_DIR=$HOME/ploomber-k8s