name: Docker Image CI (Kubernetes)
on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd tutorials/kubernetes
        docker build --tag ploomber-k8s .
    - name: Start a Docker container
      run: |
        export SHARED_DIR=$HOME/ploomber-k8s
        mkdir -p $SHARED_DIR
        docker run \
            --privileged=true -v /var/run/docker.sock:/var/run/docker.sock \
            --volume $SHARED_DIR:/mnt/shared-folder \
            --env SHARED_DIR \
            --env PLOOMBER_STATS_ENABLED=false \
            -p 2746:2746 \
            ploomber-k8s /bin/bash